server:
  port: 8999 #启动端口为8999


spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
  resources:
    static-locations:
      classpath:/META-INF/resources/,
      classpath:/resources/,
      classpath:/static/,
      classpath:/public/,
      file:${web.upload-path}


  datasource:
    url: jdbc:mysql://192.168.229.128:3306/ms?characterEncoding=UTF-8&&serverTimezone=GMT
    #    username: a
    #    password: a
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

web:
  upload-path: D:/Desktop/css/
  PDFPATH: D:/Desktop/css/
  CONFIG: my-repository-config-dev.json

